name: Publish artifacts

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    name: Build and Upload to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Build package
        run: |
          pip install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist

  create-pypi-release:
    name: Create PyPi release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Upload to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  create-github-release:
    name: Create GitHub release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Extract tag from gitref
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.vars.outputs.tag }}
          draft: True
          files: dist/*
          generate_release_notes: True
